#!/usr/bin/env bash

L1_EVENTS=PAPI_L1_DCM,PAPI_L1_DCH,PAPI_L1_DCR,PAPI_L1_DRW,PAPI_L1_DCA
L2_EVENTS=PAPI_L2_DCM,PAPI_L2_DCH,PAPI_L2_DCR,PAPI_L2_DRW,PAPI_L2_DCA
L3_EVENTS=PAPI_L3_DCM,PAPI_L3_DCH,PAPI_L3_DCR,PAPI_L3_DRW,PAPI_L3_DCA
#export PAPI_DEBUG=HIGHLEVEL
#export PAPI_HL_THREAD_MULTIPLE=1
export OMP_NUM_THREADS=1
export PAPI_REPORT=True
export PAPI_EVENTS=$L1_EVENTS,$L2_EVENTS,$L3_EVENTS
../build/omp-stream -s 4000000 -n 10
